# Generated by Django 6.0 on 2025-12-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='kubeconfig',
            field=models.TextField(blank=True, help_text='Paste the kubeconfig YAML used for deployments.', null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='kubernetes_namespace',
            field=models.CharField(default='default', max_length=200),
        ),
        migrations.AddField(
            model_name='repository',
            name='nexus_password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='nexus_registry',
            field=models.CharField(blank=True, help_text='Hostname (and optional port) of the Nexus Docker registry.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='nexus_repository',
            field=models.CharField(blank=True, help_text='Repository or project within Nexus where images will be pushed.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='nexus_username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
