# Generated by Django 6.0 on 2025-12-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployer', '0002_repository_kubeconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='commit',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='last_revision',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
